spring:
  application: 
    name: stock
  datasource: 
    url: jdbc:mysql://localhost:3306/stocks
    username: root
    password: oceanmoonfrooti
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true